### ISSUE TITLE
Broken link in Doc authoring > Overview

### ISSUE THREAD

**Issue by vvm-broadsoft** [fastai/fastai_docs#1]
Section "Modules" (http://docs.fast.ai/gen_doc.html#Modules) contains broken link "fastai.gen_doc.sgen_notebooks". 
However, sgen_notebooks script seems to be covered in http://docs.fast.ai/gen_doc.gen_notebooks.html#fastai.gen_doc.gen_notebooks, so that broken link seems to be redundant.

**Comment by sgugger** [comment]
This has been fixed, thanks for pointing it out!
