### ISSUE TITLE
class XResNet not working with mnist

### ISSUE THREAD

**Issue by kasparlund** [fastai/fastai_docs#109]
the following line fails :     
- return act_fn(self.convs(x) + self.idconv(self.pool(x))) )

because self.pool(x)) and self.convs(x) does not match

i suggest this fix in class ResBlock(nn.Module).__init__

- change self.pool   = noop if stride==1 else nn.AvgPool2d(2)
- to          self.pool   = noop if stride==1 else nn.AvgPool2d(2, ceil_mode=True)

the ResBlock.forward could also use an in place add_  although i cannot measure the difference for xresnet18:  

- act_fn(self.convs(x).add_( self.idconv(self.pool(x)))) )

**Comment by sgugger** [comment]
Thanks for suggesting the fix!
