### ISSUE TITLE
Windows compatibility + typo's

### ISSUE THREAD

**Issue by cudawarped** [fastai/fastai_docs#129]
Hi,
I am not sure if I should submit a pr for 1) Windows compatibility issues and/or 2) small typo's in the notebooks or not?
For example:
1) In [notebook2script.py](https://github.com/fastai/fastai_docs/blob/35b07e3225b0a29bd18cb51fc7df4b8f4adaa148/dev_course/dl2/notebook2script.py#L56) 
`main_dic = json.load(open(fname,'r'))`
breaks on windows and could be replaced with
`main_dic = json.load(open(fname,'r', encoding="utf-8"))`
2) At the bottom of notebook [02_fully_connected.ipynb](https://github.com/fastai/fastai_docs/blob/master/dev_course/dl2/02_fully_connected.ipynb) python is missing from the command in the last cell.

**Comment by jph00** [comment]
Sure feel free! Thanks :)
