### ISSUE TITLE
Callbacks  - "begin_epoch" always called 2x...

### ISSUE THREAD

**Issue by lessw2020** [fastai/fastai_docs#135]
Create a callback and put a print statement in the "begin_epoch"... you'll see it is always called 2x.
This messes up any attempt at tracking the % of overall run (epochs * batch_size).

**Comment by lessw2020** [comment]
Well the bug is here in notebook 9b:

 ALL_CBS = {'begin_batch', 'after_pred', 'after_loss', 'after_backward', 'after_step',
        'after_cancel_batch', 'after_batch', 'after_cancel_epoch', 'begin_fit',
        ---->  'begin_epoch', 'begin_epoch', 
'begin_validate', 'after_epoch',
        'after_cancel_train', 'after_fit'}

Note how begin_epoch is listed 2x.

**Comment by saurabh1489** [comment]
try:
            self.do_begin_fit(epochs)
            for epoch in range(epochs):
                self.do_begin_epoch(epoch) --> This calls begin_epoch()
                #if not self('begin_epoch'): self.all_batches() --> This calls begin_epoch() again.

                with torch.no_grad():
                    self.dl = self.data.valid_dl
                    if not self('begin_validate'): self.all_batches()
                self('after_epoch')

I modified the code following :
         try:
            self.do_begin_fit(epochs)
            for epoch in range(epochs):
               begin_epoch =  self.do_begin_epoch(epoch) --> This calls begin_epoch()
                #if not begin_epoch: self.all_batches() --> This calls begin_epoch() again.

                with torch.no_grad():
                    self.dl = self.data.valid_dl
                    if not self('begin_validate'): self.all_batches()
                self('after_epoch')

Now working as expected. But I am not sure of any side effects.
