### ISSUE TITLE
problem with small train datasets?

### ISSUE THREAD

**Issue by orenmel** [fastai/fastai_docs#24]
Hi. When training an imdb sentiment model using the code from:
https://github.com/fastai/fastai_docs/blob/master/docs_src/text.ipynb
but trimming train.csv to the first 10 lines, I get the following error:
.../lib/python3.7/site-packages/fastprogress/fastprogress.py:89: UserWarning: You generator is empty.
  warn("You generator is empty.")
...
File ".../lib/python3.7/site-packages/fastprogress/fastprogress.py", line 213, in on_update
    filled_len = int(self.length * val // self.total)
ZeroDivisionError: integer division or modulo by zero

**Comment by sgugger** [comment]
That's because it's too small and created an empty dataloader. You should lower the batch size or the bptt, or keep more line.
