### ISSUE TITLE
Would be nice to have imports at the top of every page/example

### ISSUE THREAD

**Issue by aakashns** [fastai/fastai_docs#27]
Thanks for the detailed docs! 

While it's mentioned on the intro page that one typically imports `*` from `fastai` and one of the applications e.g. `fastai.vision`, it is easy to miss, especially if you've arrived at the docs for a particular section by following a link.

It would be nice to have a couple of imports before every example, so one can easily follow along. I can  create a PR, but I wanted to bounce off the idea first, hence the issue.

**Comment by sgugger** [comment]
We talked about it with Jeremy and decided we only want to show the import for each overview. Note that you can always see what's imported in the first cell (hidden in html but present in the notebook). I'll push that later today.

**Comment by aakashns** [comment]
Thanks!
