### ISSUE TITLE
Probably wrong info in a sentence - Beginner's Tutorial

### ISSUE THREAD

**Issue by parthi2929** [fastai/fastai_docs#41]
Hi

[Here](https://docs.fast.ai/tutorial.data.html#A-multilabel-problem) in labels.csv, it is said that we have to add 'train' as prefix to filenames, but I already see the file names in csv having train as prefix. I am beginner newly reading these, so not sure if I am missing something so creating this issue. 

**Issue**
![image](https://user-images.githubusercontent.com/11896263/50377226-82e0fd00-063f-11e9-8e70-bf8dab2dd5b9.png)

**My analysis:**  
```
def print_N_lines(f,N):
    c = 0
    with open(f) as infile:
        for line in infile:        
            print(line.replace('\n',''))
            c += 1
            if c == N:
                break

print_N_lines(os.path.join(planet,'labels.csv'),5)  # sneak peak at labels data in labels.csv
```
Output:  
```
image_name,tags
train_31112,clear primary
train_4300,partly_cloudy primary water
train_39539,clear primary water
train_12498,agriculture clear primary road
```

**Comment by stas00** [comment]
For fastai code and docs please use: https://github.com/fastai/fastai/issues/
Kindly resubmit if it's still relevant. Thank you.
