### ISSUE TITLE
There is no docs_src folder

### ISSUE THREAD

**Issue by maxyazhbin** [fastai/fastai_docs#42]

**Comment by stas00** [comment]
What brought you to https://github.com/fastai/fastai_docs? some outdated document? in which case it'd help if you were to specify the location of that document.

docs_src migrated to https://github.com/fastai/fastai back in the fall.

**Comment by stas00** [comment]
ah, ok, the README.md was outdated. Fixed now. Please proceed to  https://github.com/fastai/fastai.
